- src/Plug.vala
See: https://github.com/elementary/switchboard-plug-parental-controls/pull/23#issuecomment-305751889
> Using null instead of a string with null

- src/Widgets/ControlPage.vala
Ensure that stack switcher is homogeneous on newer GTK
> Make Gtk.StackSwitcher homogeneous

- src/Plug.vala
- src/Translation.vala
- src/Widgets/AppChooser.vala
- src/Widgets/AppsBox.vala
- src/Widgets/ControlPage.vala
- src/Widgets/GeneralBox.vala
- src/Widgets/InternetBox.vala
- src/Widgets/UserItem.vala
- src/Widgets/UserList.vala
- src/Widgets/WeekSpinBox.vala
- src/client/AppUnavailableDialog.vala
- src/client/Client.vala
- src/daemon/Daemon.vala
- src/daemon/Interfaces.vala
- src/daemon/Process.vala
- src/daemon/Restriction.vala
- src/daemon/RestrictionController.vala
- src/daemon/Restrictions/AppRestriction.vala
- src/daemon/Restrictions/TimeRestriction.vala
- src/daemon/Restrictions/WebRestriction.vala
- src/daemon/Server.vala
- src/daemon/SessionHandler.vala
- src/daemon/SessionManager.vala
- src/daemon/UserConfig.vala
- src/shared/PAM/Reader.vala
- src/shared/PAM/Token.vala
- src/shared/PAM/Writer.vala
- src/shared/Utils.vala
Updates the FSF address in license headers (not sure how I missed these in #29)
Fixes #16
> Update FSF address

- data/meson.build
- data/pantheon-parental-controls-client.desktop.in
- src/meson.build
> Install the client & fix .desktop

- src/plug/Widgets/UserItem.vala
Fixes #49 
Load avatars from file so that they render at the correct size on HiDPI
> Fix HiDPI avatar size

- src/plug/Plug.vala
> Fix accounts link

- src/plug/Plug.vala
Alterations to get better results when searching for sub settings. See: https://github.com/elementary/applications-menu/pull/133
> Plug search improvements

- data/meson.build
Fixes a few warnings from Meson
> Meson: fix warnings from data dir

- src/plug/Widgets/ControlPage.vala
- src/plug/Widgets/GeneralBox.vala
Since what we're doing here is settings Time Limits, I think it makes sense to rename this view from "General" which means little and doesn't indicate what lives in this view
> Rename General to Time Limits

- src/plug/Widgets/ControlPage.vala
- src/plug/Widgets/GeneralBox.vala
There's a bunch of dead code here related to the dock and printers that's not being used
> GeneralBox: Remove dead code

- src/daemon/Server.vala
> Server: Code style fixes

- src/common/Constants.vala.in
> Constants: Remove unused strings

- src/daemon/Server.vala
- src/daemon/SessionHandler.vala
- src/daemon/UserConfig.vala
A change made in both #81 and #87 that could be broken out into its own commit
> UserConfig: convert get/set to properties

- src/daemon/UserConfig.vala
View with hide whitespace changes :)
> UserConfig: inline namespacing

- src/client/Client.vala
- src/common/Utils.vala
- src/daemon/AccessControlLists.vala
- src/daemon/Restrictions/TimeRestriction.vala
- src/daemon/Restrictions/WebRestriction.vala
- src/daemon/Server.vala
- src/daemon/SessionManager.vala
- src/plug/Views/AppsView.vala
This pr just addresses any linting errors people may have with the restriction-rewrite branch.
> lint changes in restriction rewrite via vala-lint

- .github/workflows/main.yml
Replaces https://github.com/elementary/switchboard-plug-parental-controls/pull/103. Does the same thing, but uses the elementary action instead of the vala-lint image
> use vala-lint action

- data/io.elementary.switchboard.parental-controls.appdata.xml.in
- meson.build
Just localization updates, but a good amount of them
> Release 3.0.1

- src/client/Client.vala
- src/common/Constants.vala.in
- src/common/meson.build
- src/plug/Plug.vala
Provides the directory where the locales are actually installed.
> l10n: Correctly setup the locales

- data/screentime-limits.policy.in.in
Fixes #160 
You can't set this property multiple times to create an array, it has to be a space separated list.
https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html
> Correctly list polkit implied permissions

- src/plug/MainView.vala
* bump copyright header
* Code style
* Remove extra grid
* Use infobar revealed property
* Can't use get_children in GTK 4, so use named children instead
> MainView: GTK4 prep

- src/plug/Views/AppsView.vala
- src/plug/Widgets/AppChooser.vala
Same as we do in startup for example
> AppChooser: subclass dialog

- src/plug/Widgets/ControlPage.vala
- src/plug/Widgets/UserItem.vala
Use the switch from Switchboard.SettingsPage instead of putting it in the sidebar
> ControlPage: use built-in switch

- src/plug/MainView.vala
Stores the sidebar position configured by the user.
> Store Sidebar Position

- .github/workflows/main.yml
- .github/workflows/release.yml
The branch still exists but seems to be behind from the main
> Actions: Use main branch
